/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumesRouteImport } from './routes/resumes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderTemplatesRouteImport } from './routes/builder/templates'
import { Route as BuilderIdRouteImport } from './routes/builder/$id'

const ResumesRoute = ResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderTemplatesRoute = BuilderTemplatesRouteImport.update({
  id: '/builder/templates',
  path: '/builder/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIdRoute = BuilderIdRouteImport.update({
  id: '/builder/$id',
  path: '/builder/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resumes': typeof ResumesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/templates': typeof BuilderTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resumes': typeof ResumesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/templates': typeof BuilderTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resumes': typeof ResumesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/templates': typeof BuilderTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resumes' | '/builder/$id' | '/builder/templates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resumes' | '/builder/$id' | '/builder/templates'
  id: '__root__' | '/' | '/resumes' | '/builder/$id' | '/builder/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumesRoute: typeof ResumesRoute
  BuilderIdRoute: typeof BuilderIdRoute
  BuilderTemplatesRoute: typeof BuilderTemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resumes': {
      id: '/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof ResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/templates': {
      id: '/builder/templates'
      path: '/builder/templates'
      fullPath: '/builder/templates'
      preLoaderRoute: typeof BuilderTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/builder/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumesRoute: ResumesRoute,
  BuilderIdRoute: BuilderIdRoute,
  BuilderTemplatesRoute: BuilderTemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
